@startuml

skinparam componentStyle rectangle

package ui {
  [Commands] ..> [Output]
  [Input]
}

package model {
' Relações de Coesão
  [Game] ..> [Board]
  [Game] ..> [Position]
  [Game] ..> [Player]
  [Board] ..> [Player]
  [Board] ..> [Position]
}

' Relações de Acoplamento
[Main] --> [Input]
[Main] --> [Commands]
[Main] --> [Game]
[Commands] -> [Game]
[Output] -up-> [Game]
[Output] -> [Board]


@enduml